# Site settings
title: Gago
description: 'Paco Gago'
url: 'pacogago.github.io'
baseurl: '/'

# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Paco Gago'
  email: contacto@franciscogago.com
  twitter_username: pacogago
  #facebook_username: joshgerdes
  github_username:  PacoGago
  #linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'posts'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
