# Site settings
title: Gago
description: 'Blog'
url: 'https://github.com/PacoGago/jekyll-uno'
baseurl:
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'https-pacogago-github-io'
avatarurl: 'https://raw.githubusercontent.com/PacoGago/pacogago.github.io/master/images/profile.jpg'
# youtubeurl:  'https://www.youtube.com/channel/UCHnN13dHhdYq8nx5HEXmMxg'

author:
  name: 'Francisco Gago'
  email: contacto[at]franciscogago[dot]com
  twitter_username: pacogago
  facebook_username: pacogago
  github_username: pacogago
  linkedin_username:  pacogag

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
