# Site settings
title: Hoang Dang
description: 'A DevOps Craftsman'
url: 'https://github.com/PacoGago/jekyll-uno'
baseurl:
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'theroot'
gravatarurl: 'https://www.gravatar.com/avatar/2a3cb6f253bbd6e6c2c60a963cd5616b'
youtubeurl:  'https://www.youtube.com/channel/UCHnN13dHhdYq8nx5HEXmMxg'

author:
  name: 'Hoang Dang'
  email: hoangdangninh[at]gmail[dot]com
  twitter_username: hoangdangninh
  facebook_username: hdnroot
  github_username: hoangdangninh
  linkedin_username:  hdroot

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
