# Setup
title:               Gago
tagline:             'Software Engineer'
description:         'A personal blog'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Gago
  url:               https://twitter.com/pacogago
  email:             contacot@franciscogago.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
